---
engines:
  eslint:
    enabled: true
    base_sub_dir: "src/http/ui"
    exclude_paths:
      - "dist/**"
      - "node_modules/**"
  typescript:
    enabled: true
    base_sub_dir: "src/http/ui"
